# Generated by Django 4.1.2 on 2022-10-27 11:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_released', models.DateField(default=datetime.datetime.today)),
                ('like', models.IntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')], default=0)),
                ('artiste_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music_app.artiste')),
            ],
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music_app.song')),
            ],
        ),
    ]
