# Generated by Django 4.1.2 on 2022-10-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lyrics',
            new_name='Lyric',
        ),
    ]
